### ISSUE TITLE
Wrong Converting

### ISSUE THREAD

**Issue by Ikedia** [weareindi/atom--var-that-color#1]
Hi! Very useful plugin. I really liked it, but it converts colors to rgb with mistakes.
For example, #9D6B37 (sepia-skin) converted to rgb(158, 91, 64), but should convert to rgb(157, 107, 55).
Also, would be good to have just naming (without conversion to rgb) option.

Thank you!

**Comment by loz-archer** [comment]
That's for letting me know - I'm looking into a fix now.

I'll also take your suggestions into consideration. I'll focus on getting the rgb conversion correct first ;)

**Comment by loz-archer** [comment]
The problem lays with 'Name That Color' (http://chir.ag/projects/ntc/).
When a hex colour you want converted (eg. #9D6B37) doesn't have an exact match; NTC selects a name/colour it thinks is "close enough" to a match.

I'm using the output from 'Name The Color' and pushing that through my hex-to-rgb conversion rather than using the selected hex code you want converted.

I actually feel the way it currently works is correct but I will implement a quick fix now that indicates when an exact match was not found by NTC.

**Comment by loz-archer** [comment]
Actually, scrap that - I've changed my mind.
The package now converts the hex selected to the rgb you're expecting.

I'm just about to publish the fix.

**Comment by Ikedia** [comment]
Great job! Thanks for fast turnaround and useful plugin. Now works well. Bug is resolved.
